// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWQpYbsQaWhSZ3IDO4k2Q1HtrzIoo47tE',
    appId: '1:350236915817:web:9daa171cf825bb30d6caf8',
    messagingSenderId: '350236915817',
    projectId: 'attendx-18717',
    authDomain: 'attendx-18717.firebaseapp.com',
    storageBucket: 'attendx-18717.firebasestorage.app',
    measurementId: 'G-N1RMM5P0HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD49f3CSI-DdceIMnUqBVlNUZS0bCs4mfI',
    appId: '1:350236915817:android:f527e5e39fdf3d2bd6caf8',
    messagingSenderId: '350236915817',
    projectId: 'attendx-18717',
    storageBucket: 'attendx-18717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF0NxKQZwwQ2-Hx_R8hykVeQNgJUAvAp8',
    appId: '1:350236915817:ios:8bba6d821e5cfe3cd6caf8',
    messagingSenderId: '350236915817',
    projectId: 'attendx-18717',
    storageBucket: 'attendx-18717.firebasestorage.app',
    iosBundleId: 'com.example.attendx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF0NxKQZwwQ2-Hx_R8hykVeQNgJUAvAp8',
    appId: '1:350236915817:ios:8bba6d821e5cfe3cd6caf8',
    messagingSenderId: '350236915817',
    projectId: 'attendx-18717',
    storageBucket: 'attendx-18717.firebasestorage.app',
    iosBundleId: 'com.example.attendx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWQpYbsQaWhSZ3IDO4k2Q1HtrzIoo47tE',
    appId: '1:350236915817:web:d6bcddfe2b765205d6caf8',
    messagingSenderId: '350236915817',
    projectId: 'attendx-18717',
    authDomain: 'attendx-18717.firebaseapp.com',
    storageBucket: 'attendx-18717.firebasestorage.app',
    measurementId: 'G-R25JG6JV70',
  );
}
